### ISSUE TITLE
To ensure that this project is an improvement, the weaknesses in Knockout must be considered

### ISSUE THREAD

**Issue by craigfowler** [csf-dev/rxjs-viewmodel#9]
I quite like knockout JS and anything in do here is likely to be heavily influenced by that.

I'm not yet sure whether I want to actually become a fork of KO, but whether I do our not, this comment sums up some of KO's weaknesses which I'd like to address.

https://github.com/knockout/tko/issues/74#issuecomment-418649990

**Comment by craigfowler** [comment]
One by one, those weaknesses are:

* Live parsing of HTML nodes without precaution of what properties are being hit
* Nesting of cloned data contexts
* Live instead of compiled preprocessing
* Naïve array reconciliation algorithm
* Data-bind syntax
* Implicit context naming ($parent etc..)
* Webcomponents are KO locked in

**Comment by craigfowler** [comment]
I believe that the reference to **nesting of cloned data contexts** refers to the [data context class].

[data context class]: https://github.com/knockout/knockout/blob/master/src/binding/bindingAttributeSyntax.js#L30

**Comment by craigfowler** [comment]
I think that the live/compiled preprocessing is all about the mixture of the [live expression rewriting] *which is just live string manipulation* and then also [the live template loading] *which will merrily parse strings again and again without caching the compiled template*.

[live expression rewriting]: https://github.com/knockout/knockout/blob/master/src/binding/bindingProvider.js#L67
[the live template loading]: https://github.com/knockout/knockout/blob/master/src/components/defaultLoader.js#L102

**Comment by craigfowler** [comment]
I can definitely see the [live parsing of HTML nodes](https://github.com/knockout/knockout/blob/master/src/components/defaultLoader.js#L102) - this occurs as part of the component loading code.  What's rather disappointing is that there's no cache for the parsed nodes, so each time the template is used, its markup is parsed again.

**Comment by ryansolid** [comment]
Yeah I wasn't directly looking at the code when I made that comment. More of just sort of tallying up the things I'd seen as I've used Knockout over the years, and tried to make my own clones. A while back concerned with the bloat I tried to write my own replacement mimicking many of Knockouts behaviors and found that while I could get significantly better performance it was never that good, and I attributed it to the approach.

To be fair while I've hit walls with my efforts in the past in that direction (which has led me to JSX/Babel precompilation the past year), I've seen some recent libraries that do that similar walk of already rendered dom nodes and context nesting to good effect. So maybe it isn't that flawed of an approach and just needs some revision.  [DomC](https://github.com/Freak613/domc) as seen on the [JS Framework Benchmark](https://github.com/krausest/js-framework-benchmark) as arguably the most performant library uses a similar approach.  So there are options here I think.

**Comment by craigfowler** [comment]
I hear that. This project may indeed come to nothing, but I needed to give it a shot because KO is *so close* to what I want, but there's a few things I'd like to do differently. If it wasn't for "the core concept of an observable" that I wanted to swap out (for rxjs) I might have started this as a fork.
